kubernetesClusterDomain: cluster.local

rqWorker:
  replicas: 1
  worker:
    image:
      repository: stackblaze/rq-worker
      tag: latest
      pullPolicy: Always
    env:
      redisHost: "redis-master"
      redisPort: "6379"
      redisUsername: ""
      redisPassword: ""