kubernetesClusterDomain: cluster.local
rqWorker:
  replicas: 1
  worker:
    env:
      redisHost: redis-service
      redisPort: "6379"
    image:
      repository: stackblaze/rq-worker
      tag: latest
