apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rq-worker.fullname" . }}-rq-worker
  labels:
    {{- include "rq-worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rqWorker.replicas }}
  selector:
    matchLabels:
      app: rq-worker
      {{- include "rq-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: rq-worker
        {{- include "rq-worker.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: {{ .Values.rqWorker.worker.env.redisHost | quote }}
        - name: REDIS_PORT
          value: {{ .Values.rqWorker.worker.env.redisPort | quote }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.rqWorker.worker.image.repository }}:{{ .Values.rqWorker.worker.image.tag | default .Chart.AppVersion }}
        name: worker
        resources: {}
