apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rq-worker.fullname" . }}-rq-worker
  labels:
    {{- include "rq-worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rqWorker.replicas }}
  selector:
    matchLabels:
      app: rq-worker
      {{- include "rq-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: rq-worker
        {{- include "rq-worker.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: worker
        image: {{ .Values.rqWorker.worker.image.repository }}:{{ .Values.rqWorker.worker.image.tag | default .Chart.AppVersion }}
        env:
        - name: REDIS_HOST
          value: {{ .Values.rqWorker.worker.env.redisHost | quote }}
        - name: REDIS_PORT
          value: {{ .Values.rqWorker.worker.env.redisPort | quote }}
        {{- if .Values.rqWorker.worker.env.redisUsername }}
        - name: REDIS_USERNAME
          value: {{ .Values.rqWorker.worker.env.redisUsername | quote }}
        {{- else if .Values.rqWorker.worker.env.redisUsernameSecret }}
        - name: REDIS_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.rqWorker.worker.env.redisUsernameSecret.name }}
              key: {{ .Values.rqWorker.worker.env.redisUsernameSecret.key }}
        {{- end }}
        {{- if .Values.rqWorker.worker.env.redisPassword }}
        - name: REDIS_PASSWORD
          value: {{ .Values.rqWorker.worker.env.redisPassword | quote }}
        {{- else if .Values.rqWorker.worker.env.redisPasswordSecret }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.rqWorker.worker.env.redisPasswordSecret.name }}
              key: {{ .Values.rqWorker.worker.env.redisPasswordSecret.key }}
        {{- end }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        resources: {}